<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1 (Total Recall)

| Term       | Brief Description                                                                        |
|------------|------------------------------------------------------------------------------------------|
| Subsetting | To split the data into different, smaller subsets. (analogy to set theory) <br/>  _To select_ |
| Indexing   | To pick a certain element or entry in list                                               |
| Slicing    | To pick a certain index in a list <br/> _To select a range of elements_                      |
| Masking    | To pick the entries with a desired criteria (e.g. x > 4)                                 |

### Exercise 2 (show me the 'odd' letters)

In [1]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [85]:
# Goal: To get odd letter
num_let = np.array(np_array_2d[:,0])
odd = np.array(np.float64(num_let) % 2 == 1)   # np.float64 floats all array str into floats, which can modulo 2 to check for odd.
np_array_2d[odd,1]   # Mask to determine which odd numbers to pick from, and 1 to indicate the index which is pulled (letter)
print(np_array_2d[odd,1])

['A' 'C' 'E' 'G' 'I']


### Exercise 3

In [83]:
help = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])
under = np.array(help[:,:] < 50)    # Check if array has any value thats below 50
over = np.array(help[:,:] > 50)
equal = np.array(help[:,:] == 50)
help[under.astype(bool)] = -1       # astype(bool) to change True to value of -1  
help[over.astype(bool)] = +1        # astype(bool) to change True to value of 1
help[equal.astype(bool)] = 0        # astype(bool) to change True to value of 0
print(help)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


note to mentor: is there a way to compact the code because it feels like I'm typing a lot of repeated steps?