<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [1]:
import numpy as np

## 1.1 Let’s compare

In [ ]:
# To have a list, we have to define it (for python)
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

# To have an array, we have to define it (for Numpy)
np_super_names = np.array(['Black Widow', 'Iron Man', 'Doctor Strange'])
np_real_names = np.array(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

# Dictionary (Note the ':' which separates stuff)
superhero_info = {
    'Natasha Romanoff': 'Black Window',
    'Tony Stark': 'Iron Man',
    'Stephen Strange': 'Doctor Strange'
}

## 1.2 Accessing data from a list (or array)

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

py_real_names[0]
# Specifies for the index starting from 0.

'Natasha Romanoff'

In [6]:
py_super_names[0]

'Black Widow'

We can also use negative numbers for indexing to pull up the index starting from the back.

In [8]:
py_super_names[2] # Forward indexing, to get the second index from the front

'Doctor Strange'

In [9]:
py_super_names[-1] # Reverse Indexing, to get the first index from the back

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [11]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [12]:
superhero_info['Natasha Romanoff']

'Black Widow'

In [15]:
superhero_info.keys() # Shows the keys, i.e. first values

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [17]:
superhero_info.values() # Shows the values for the specific keys

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [20]:
# It is possible to have a 2D list/array as follow:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'], 
                     ['Stephen Strange', 'Doctor Strange']]
# Lists within lists :O Inception!

# 2 Lists vs. Arrays

## 2.1 Size

In [21]:
# Use of len() function to show the amount of elements in lists or arrays
py_list_2d = [[1,'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10, 'J']]

np_array_2d = np.array(py_list_2d)            # reuses the python list to create a new array

In [24]:
print(len(py_list_2d))
print(len(np_array_2d))
print(np_array_2d.shape) 
# Note how shape is NOT a function, but is a property or attribute of the Numpy array

10
10
(10, 2)


## 2.2 Arrays are fussy about type

In [25]:
# Arrays are particular about single data types
# lists are more accommodating
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [28]:
py_list
np_array 
# Note that we have to be careful for arrays (use of astypes() are required)

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [31]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array + 10 # Adds 10 to every entry
# Note that this won't work for python
# py_list + 10 # Try removing the first '#' in this row to convince yourself

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [32]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [36]:
print(py_list_1 + py_list_2)
np_array_1 + np_array_2
# Note that adding lists appends them, while adding arrays is an element-wise

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [38]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(py_list*2)
np_array*2
# Note that multiplying lists makes them grow, but arrays multiplies its elements by the number.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [39]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

np_array**2
# py_list**2 # will not work (try to remove '#' to convince yourself)

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
py_list == 3     # This works, but note that it checks if the variable is equal to 3

False

In [44]:
np_array == 3    # This checks all indexes in the array
#np_array > 3     # Note: This won't work (try removing the '#' in the line)

array([False, False,  True, False, False])

## 2.8 Mathematics

In [47]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
print(sum(py_list)) # sum() is a base python function
print(max(py_list)) # max() is a base python function
print(min(py_list)) # min() is a base python function
# Note: py_list.sum() WILL NOT WORK
print(np_array.sum())
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.std())  # Standard deviation

15
5
1
15
5
1
3.0
1.4142135623730951


## Footnotes