<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

**Subsetting** = 'Select' (Think set theory, it's the exact same thing!)
- **Indexing** = Selecting 1 element
- **Slicing** = Selecting a range of elements.

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [11]:
import numpy as np
py_list = ['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']
np_array = np.array(py_list)

x = py_list
# x = np_array   # Pick One!!

x[0]           # First element
x[-1]          # Last element
x[0:3]         # Index 0 to 2
x[1:6]         # Indexes 1-5 (or 2nd entry to 6th entry)
x[1:6:2]       # Index 1 to 5 in steps of 2
x[5:]          # Index 5 to the end
x[:5]          # Index 0 to 5
x[5:2:-1]      # Index 5 to 3 but in reverse.
x[::-1]        # Reverses the entire list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [13]:
# We can subset via Masking!
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask    # Shows which ones obey the rule of > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [15]:
np_array[my_mask]   # This returns the elements that are ONLY TRUE.

array([ 4,  5,  6,  7,  8,  9, 10])

In [16]:
np_array[np_array > 3]    # This is a more compact version of the above

array([ 4,  5,  6,  7,  8,  9, 10])

Note the following examples and how different symbols can be used to further filter the elements we want:

In [21]:
np_array[~(np_array > 3)]   # '~' indicates NO

array([1, 2, 3])

In [22]:
np_array[(np_array > 3) & (np_array < 8)]   # '&' means AND.

array([4, 5, 6, 7])

In [23]:
np_array[(np_array < 3) | (np_array > 8)]   # '|' indicates OR (similar to math)

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [25]:
# Increasing the dimension! Lists within Lists!! Arrays within Arrays!! Dreams within dreams!! (hsr reference)

py_list_2d = [[1,'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10,'J']]
np_array_2d = np.array(py_list_2d)

In [27]:
py_list_2d[3]  # Pulls the 4th position (Note how it is another array)

[4, 'D']

In [30]:
py_list_2d[3][0]     # First element of position 4 (index 3)
# OR np_array_2d[3,0]

4

In [33]:
py_list_2d[:3]      # First 3 elements of the array!!
# OR np_array_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

Note the differences between the lists & arrays:

In [39]:
py_list_2d[:3][0]   # This pulls up the FIRST ENTRY of the list WITH the FIRST 3 indexes.

[1, 'A']

In [40]:
np_array_2d[:3, 0]   # This pulls up the FIRST ELEMENT of each of the FIRST 3 indexes.

array(['1', '2', '3'], dtype='<U21')

In [41]:
py_list_2d[3:6][0]   # This pulls up the FIRST ENTRY of the list WITH the FINAL 3 indexes.

[4, 'D']

In [43]:
np_array_2d[3:6, 0]   # This pulls up the FIRST ELEMENT of each of the LAST 3 indexes.

array(['4', '5', '6'], dtype='<U21')

In [45]:
np_array_2d[:, 0]     # This pulls up the FIRST ELEMENT of each index.

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

NumPy arrays are good for math operations, as long as you don't change their size.

In [47]:
x = [1, 2] * 5     # to append the lists x 5
x 

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [53]:
# To grow a list via appending one element at a time (SLOW)
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]

# To grow a list via appending one element at a time (SLOW-ish)
y = [1]
y += [2]
y += [3]
y += [4]

# To grow a list via manually appending (fast-ish)
z = [1]
z.append(2)
z.append(3)
z.append(4)

print(x, y, z)

[1, 2, 3, 4] [1, 2, 3, 4] [1, 2, 3, 4]


In [55]:
# to append it together
x = [1, 2, 3]
x += [4, 5, 6]

# to extend! '.extend'
y = [1, 2, 3]
y.extend([4, 5, 6])

# to append but BE CAREFUL!
z = [1, 2, 3]
z.append([4, 5, 6])   # THIS WILL APPEND THE LIST [4, 5, 6] AS AN ENTRY.

print(x, y, z)

[1, 2, 3, 4, 5, 6] [1, 2, 3, 4, 5, 6] [1, 2, 3, [4, 5, 6]]


# Some loose ends

## 1.5 Tuples

A tuple is denoted by '( )' and cannot be changed!!

In [59]:
a = (1, 2, 3)   # Define tuple
print(a[0])     # Access data, first entry

# The following will not work as you cant change it
# a[0] =- 1
# a[0] += [10]

1


## 1.6 Be VERY careful when copying

Note: DO NOT DO THE FOLLOWING!!

In [61]:
x = [1, 2, 3]
y = x
z = x
# DO NOT DO THIS!

DO THE FOLLOWING INSTEAD:

In [62]:
x = [1, 2, 3]
y = x.copy()
z = x.copy()

## Footnotes